# PyTorch Basics with Examples
This notebook demonstrates various PyTorch operations such as tensor creation, initialization, reshaping, and mathematical operations.

---

## 1. Importing Libraries and Checking PyTorch Version
We start by importing the necessary libraries and verifying the PyTorch version.


In [2]:
# Importing required libraries
import torch
import numpy as np

# Display PyTorch version
print(f"Current PyTorch Version: {torch.__version__}")

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


Current PyTorch Version: 2.5.1+cu121
Using device: cpu


## 2. Tensor Creation and Initialization
We demonstrate how to create and initialize tensors using various methods.


In [3]:
# Create a new tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)
print(f"Tensor: \n{tensor}\nType: {tensor.dtype}\nDevice: {tensor.device}\nShape: {tensor.shape}")

# Tensor Initialization Methods
empty_tensor = torch.empty(2, 3)
zeros_tensor = torch.zeros((3, 3))
rand_tensor = torch.rand((3, 3))
eye_tensor = torch.eye(5, 5)  # Diagonal matrix
arange_tensor = torch.arange(start=0, end=5, step=1)
linspace_tensor = torch.linspace(start=0.1, end=1, steps=10)
normal_tensor = torch.empty(2, 3).normal_(mean=0, std=1)
uniform_tensor = torch.empty(2, 3).uniform_(0, 1)
diag_tensor = torch.diag(torch.ones(3))

# Display initialized tensors
print(f"Random Tensor: \n{rand_tensor}")
print(f"Diagonal Tensor: \n{diag_tensor}")


Tensor: 
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Type: torch.float32
Device: cpu
Shape: torch.Size([2, 3])
Random Tensor: 
tensor([[0.5482, 0.4427, 0.8040],
        [0.7555, 0.8627, 0.0284],
        [0.7924, 0.5963, 0.4813]])
Diagonal Tensor: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## 3. Basic Tensor Operations
We perform basic arithmetic operations on tensors, including addition, subtraction, division, and exponentiation.


In [4]:
# Basic Tensor Operations
x = torch.tensor([-1, 2, 3])
y = torch.tensor([1, 2, 3])
z_add = x + y
z_sub = x - y
z_div = torch.true_divide(x, y)
z_pow = x.pow(2)

print(f"Addition: {z_add}\nSubtraction: {z_sub}\nDivision: {z_div}\nPower: {z_pow}")


Addition: tensor([0, 4, 6])
Subtraction: tensor([-2,  0,  0])
Division: tensor([-1.,  1.,  1.])
Power: tensor([1, 4, 9])


## 4. Matrix Operations
This section covers matrix multiplication, broadcasting, and advanced operations like dot products and batch matrix multiplications.


In [5]:
# Matrix Multiplications
mat1 = torch.rand((2, 5))
mat2 = torch.rand((5, 3))
mat_mult = torch.mm(mat1, mat2)
print(f"Matrix Multiplication Result: \n{mat_mult}")

# Broadcasting
x1 = torch.rand(5, 5)
x2 = torch.rand(1, 5)
broadcast_result = x1 - x2
print(f"Broadcast Result: \n{broadcast_result}")


Matrix Multiplication Result: 
tensor([[1.5986, 1.1453, 0.4412],
        [1.7125, 1.0257, 0.7732]])
Broadcast Result: 
tensor([[-0.0446, -0.7520, -0.2719, -0.5760, -0.1463],
        [ 0.7172, -0.4574,  0.2537, -0.2143, -0.6114],
        [ 0.5646, -0.6743, -0.1540, -0.8040, -0.6644],
        [ 0.1420, -0.0947,  0.2143, -0.6385, -0.5012],
        [ 0.4302, -0.2654,  0.2967, -0.8954,  0.0660]])


## 5. Reshaping and Indexing
Learn how to reshape tensors and perform advanced indexing techniques.


In [6]:
# Reshaping Tensors
x = torch.arange(9)
reshaped = x.view(3, 3)
transposed = reshaped.t()
print(f"Reshaped Tensor: \n{reshaped}\nTransposed Tensor: \n{transposed}")

# Indexing and Conditional Selection
x = torch.arange(10)
indices = [2, 5, 8]
selected = x[indices]
print(f"Selected Indices: {selected}")


Reshaped Tensor: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Transposed Tensor: 
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
Selected Indices: tensor([2, 5, 8])
